# -*- coding: utf-8 -*-
"""K-NEARST NEIGHBOR

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vC3PeYE9sJlWb6R3mSXd69Go5qR38TRM
"""

# memanggil dataset iris
from sklearn.datasets import load_iris
iris_ku = load_iris()

# simpan data fitur/kolom x dan target y
X = iris_ku.data
Y = iris_ku.target

# simpan nama fitur
feature_names = iris_ku.feature_names
target_names = iris_ku.target_names

# tampil nama fitur
print("Feature names :", feature_names)
print("Target names :", target_names)

# x dan y adalah numpy
print("\nType of x is:", type(X))

# tampilkan 5 baris pertama
print("\nFirst 5 row of X:\n", X[:5])

# fitur x dan target y
X = iris_ku.data
Y = iris_ku.target

# splitting x dan y untuk data latih dan uji
from sklearn.model_selection import train_test_split
X_latih, X_tes, Y_latih, Y_tes = train_test_split(X, Y, test_size=0.4, random_state=1)

# tampilkan data fitur latih dan uji
print(X_latih.shape)
print(X_tes.shape)

# tampilkan data fitur latih dan uji
print(Y_latih.shape)
print(Y_tes.shape)

# pelatihan pada data latih menggunakan kn(k=3)
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=21)
knn.fit(X_latih, Y_latih)

# melakukan prediksi pada data uji
Y_prediksi = knn.predict(X_tes)

# perbandingan nilai aktual (y_tes) dengan nilai prediski (y_prediksi)
from sklearn import metrics
print ("Akurasi model knn :", metrics.accuracy_score(Y_tes, Y_prediksi))

# prediksi menggunakan data sampel dibuat sendiri
contoh = [[3, 5, 4, 3], [2, 3, 5, 5]]
preds = knn.predict(contoh)
pred_species = [iris_ku.target_names[p] for p in preds]
print("Prediksi :", pred_species)

# saving the model
import joblib
joblib.dump(knn, 'iris_knn.pkl')